services:
    app:
        container_name: app
        build: .
        volumes:
            - .:/opt/app
            - /opt/app/node_modules
        restart: always
        entrypoint: npm run dev
        depends_on:
            - mongo
        ports:
            - 5173:5173
        env_file:
            - .env
    mongo:
        container_name: mongo
        image: mongo:latest
        restart: always
        ports:
            - 27017:27017
        command: mongod --storageEngine=wiredTiger
        volumes:
            - data:/data/db

    mongo-express:
        image: mongo-express:1.0.2-20-alpine3.19
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_URL: mongodb://mongo:27017
            ME_CONFIG_BASICAUTH: false

volumes:
    data:
